### PR TITLE
Set default environment hooks for PATH, PYTHONPATH, and LD_LIBRARY_PATH.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Implements the resolution of #7.

This package should provide environment hooks for setting up a standard filesystem hierarchy in the ROS installation prefix (e.g. `/opt/ros/crystal/`). The hooks considered "standard" at this time are
* putting `bin` on `PATH`
* putting the python installation directory `lib/python${PYTHON_MAJOR_MINOR}/site-packages` on `PYTHONPATH`.
* putting `lib` on `LD_LIBRARY_PATH`

Previous iterations of this package also put `lib/${MULTIARCH_TRIPLET}` (e.g. `lib/x86_64-linux-gnu`) on `LD_LIBRARY_PATH` for third party packages that install into that directory. However, as of bouncy, installing into a multiarch dir when specifying a non-standard Debian
package root no longer occurs. It appears that this behavior was a bug or misbehavior that was fixed upstream in the Bionic toolchain.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
While this package is not covered by CI (the changes here have been tested locally) I am using this PR to aggregate a number of PRs updating environment hooks for ament packages that did not declare their own and the CI for those packages is linked here:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5272/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2028/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4388/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5251/)

**Comment by clalancette** [comment]
> Previous iterations of this package also put `lib/${MULTIARCH_TRIPLET}` (e.g. `lib/x86_64-linux-gnu`) on `LD_LIBRARY_PATH` for third party packages that install into that directory. However, as of bouncy, installing into a multiarch dir when specifying a non-standard Debian
> package root no longer occurs. It appears that this behavior was a bug or misbehavior that was fixed upstream in the Bionic toolchain.

A couple of things are bothering me a bit about this statement:

1.  This is fixed in the Bionic toolchain.  Crystal is still going to be targeting Xenial, so is that going to be a problem on Xenial?
1.  That this was a bug/misbehavior in the first place.  It seems to me that even if you aren't installing to system-root locations, you still might want to have MULTIARCH triplet patterns (so you could install side cross-compilers, for instance).  If this isn't needed to make things work, that's fine, but it still seems odd, and maybe the case that a bug was *introduced* in Bionic that causes this to no longer work.

**Comment by clalancette** [comment]
Oh, and finally; how do I go about testing that this does the right thing locally?

**Comment by nuclearsandwich** [comment]
> 1\. This is fixed in the Bionic toolchain.  Crystal is still going to be targeting Xenial, so is that going to be a problem on Xenial?

This package is only needed to provide the workspace setup scripts when installing ROS 2 via system package management (i.e. debs or rpms via apt or dnf). We are only providing Bionic debs for Crystal so this package needs only support bionic's toolchain for the crystal release. A "backport" of this update for someone who wanted to produce system packages for Crystal on Xenial would require re-instating the library hook which adds the multiarch directory to LD_LIBRARY_PATH.

> 2\. It seems to me that even if you aren't installing to system-root locations, you still might want to have MULTIARCH triplet patterns (so you could install side cross-compilers, for instance).  If this isn't needed to make things work, that's fine, but it still seems odd, and maybe the case that a bug was _introduced_ in Bionic that causes this to no longer work.

I looked and couldn't find a documentation trail for this change. But when I was rolling betas I was equally flummoxed to find the multiarch directories being used when installing outside of the debian root which is why the current change feels like the "return to normality" to me.


> Oh, and finally; how do I go about testing that this does the right thing locally?

1. cd into a ROS 2 workspace with a clean install space and the repos ament_package and ament_cmake
2. `colcon build --merge-install --packages-up-to ament_cmake_core`
3. export an environment variable like `ROS_INSTALL_PREFIX=$(pwd)/install`
3. Source the environment, i.e. `. install/setup.bash`
3. cd into the ros_workspace source directory
4. `mkdir build && cd build`
5. `cmake .. -DCMAKE_PREFIX_PATH=${ROS_INSTALL_PREFIX} -DCMAKE_INSTALL_PREFIX=${ROS_INSTALL_PREFIX}`
6. `make && make install`
7. `mkdir $ROS_INSTALL_PREFIX/bin` (needed to make the path hook trigger when no binaries are installed)
8. in a fresh terminal source your preferred setup script from `$ROS_INSTALL_PREFIX`
8. [ ] Check `PATH` includes `$ROS_INSTALL_PREFIX/bin`
9. [ ] Check `LD_LIBRARY_PATH` includes `$ROS_INSTALL_PREFIX/lib`
10. [ ] Check `PYTHONPATH` includes `$ROS_INSTALL_PREFIX/lib/python$MAJOR.$MINOR/site-packages`

**Comment by clalancette** [comment]
Excellent, thanks for the instructions.  Just FYI that I modified them a bit to add a new step to source the workspace in between the `colcon` build and moving into the ros_workspace directory.  I checked everything out and it looked OK to me.  This all seems OK to me, so I'm going to approve it.

**Review by clalancette — APPROVED** [review]

**Comment by jacobperron** [comment]
> However, as of bouncy, installing into a multiarch dir when specifying a non-standard Debian
package root no longer occurs. It appears that this behavior was a bug or misbehavior that was fixed upstream in the Bionic toolchain.

In Ubuntu Focal, we're seeing libraries being installed into multiarch directories again. I suspect that a bug was introduced upstream in Bionic and restored in Focal.

**Pull request merged**
